[package]
name = "jujutsu-kaisen-api"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
actix-web = "4.9.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
wiremock = "0.6.2"
reqwest = { version = "0.12.7", default-features = false, features = ["json", "rustls-tls", "cookies"] }
